spring:
  application:
    name: microservice-mediscreen-Main

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
