services:
  discovery:
    container_name: Discovery
    image: mediscreen-server:v1.0.0
    ports:
      - 8761:8761

  mediscreen:
    image: mediscreen:v1.0.0
    container_name: Mediscreen
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - noteapp
      - patientapp
      - discovery

    environment:
      eureka.client.serviceUrl.defaultZone: http://discovery:8761/eureka


  noteapp:
    image: noteapp
    container_name: noteApp
    depends_on:
      - Mongo
      - discovery

    ports:
      - 9003:9003
    environment:
      SPRING_DATA_MONGODB_HOST: mongo:27017
      eureka.client.serviceUrl.defaultZone: http://discovery:8761/eureka
    build:
      context: .


  Mongo:
    image: mongo
    container_name: Mongo
    restart: always
    expose:
      - 27017
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=noteapp
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
    volumes:
      - ./mongo-data:/var/lib/mongo/data

  patientapp:
    image: patientapp:v1.0.0
    container_name: PatientApp
    ports:
      - 9002:9002
    depends_on:
        - discovery
        - db
    environment:
      eureka.client.serviceUrl.defaultZone: http://discovery:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mediscreen
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    build:
      context: .




  db:
    image: postgres
    container_name: Postgres
    restart: always
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=mediscreen
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/scriptSQL.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./sql/scriptSQL.sql:/docker-entrypoint-initdb.d/insertData.sql

networks:
  mongo_net:
    driver: bridge
    external: true

volumes:
  postgres-data:








